name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run PlatformIO
        uses: platformio/platformio-action@v2
        with:
          version: 6
          command: |
            run

      
          
      - name: Archive built firmware
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: |
            .pio/build/**/firmware*.bin
