name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Latest
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install -U platformio

      - name: Run PlatformIO
        run: platformio run

      - name: Compile the firmware
        run: platformio run --silent -e STM32F103RET6_creality ; echo "done" >|"/tmp/ipc"

      - name: Archive built firmware
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: |
            .pio/build/**/firmware*.bin
